{"name": "测试数据：【 wintest，123456，True，0，登录成功】", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x10b574370>\nusername = 'wintest', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success\n\ntestcases/api_test/test_03_login.py:30: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}], "start": 1744699252143, "stop": 1744699252144}], "attachments": [{"name": "log", "source": "93364f0b-7dfd-41bf-8fd8-3fd482c6bae7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2e02cb5d-fe88-491b-b5ed-113f664255d8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "0"}, {"name": "except_msg", "value": "'登录成功'"}], "start": 1744699252084, "stop": 1744699252144, "uuid": "c2427677-033b-4a09-9aaa-8c10d4a8d798", "historyId": "4ab02ebad4baabe28d2fb7352ad2343a", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "192.168.10.5"}, {"name": "thread", "value": "23437-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}