{"name": "用户注册登录修改--预期失败", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nassert False is True\n +  where False = <core.result_base.ResultBase object at 0x10bc1a2e0>.success", "trace": "self = <testcases.scenario_test.test_02_register_login_update.TestRegLogUpdate object at 0x10bc2f6a0>\ntestcase_data = {'except_code': 4005, 'except_msg': '修改的用户ID不存在', 'except_result': False, 'login': {'admin_pwd': '123456', 'admin_user': 'wintest'}, ...}\n\n    @allure.story(\"用例--注册/登录/修改--预期失败\")\n    @allure.description(\"该用例是针对 注册-登录-修改 场景的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录修改--预期失败\")\n    @pytest.mark.multiple\n    @pytest.mark.usefixtures(\"delete_register_user\")\n    def test_user_register_login_update_fail(self, testcase_data):\n        username = testcase_data[\"register\"][\"username\"]\n        password = testcase_data[\"register\"][\"password\"]\n        telephone = testcase_data[\"register\"][\"telephone\"]\n        sex = testcase_data[\"register\"][\"sex\"]\n        address = testcase_data[\"register\"][\"address\"]\n        admin_user = testcase_data[\"login\"][\"admin_user\"]\n        admin_pwd = testcase_data[\"login\"][\"admin_pwd\"]\n        new_password = testcase_data[\"update\"][\"new_password\"]\n        new_telephone = testcase_data[\"update\"][\"new_telephone\"]\n        new_sex = testcase_data[\"update\"][\"new_sex\"]\n        new_address = testcase_data[\"update\"][\"new_address\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = register_user(username, password, telephone, sex, address)\n        step_1(username, password, telephone, sex, address)\n>       assert result.success is True, result.error\nE       AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nE       assert False is True\nE        +  where False = <core.result_base.ResultBase object at 0x10bc1a2e0>.success\n\ntestcases/scenario_test/test_02_register_login_update.py:99: AssertionError"}, "description": "该用例是针对 注册-登录-修改 场景的测试", "steps": [{"name": "步骤1 ==>> 注册用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "telephone", "value": "'13599999999'"}, {"name": "sex", "value": "'1'"}, {"name": "address", "value": "'深圳市宝安区'"}], "start": 1744699199652, "stop": 1744699199652}], "attachments": [{"name": "log", "source": "c35cd51b-2fad-4f0b-8dd4-07fcde065866-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f1f0feeb-5969-42d9-9f19-62fb93f51670-attachment.txt", "type": "text/plain"}], "start": 1744699199567, "stop": 1744699199653, "uuid": "c542fd38-aaf5-42ca-a7c4-ae27d77d8ba9", "historyId": "5e88704a520d70faf3165b42517fe6c2", "testCaseId": "b56ec6e5f1e8b3339a5dd14be9d281c0", "fullName": "testcases.scenario_test.test_02_register_login_update.TestRegLogUpdate#test_user_register_login_update_fail", "labels": [{"name": "epic", "value": "针对业务场景的测试"}, {"name": "feature", "value": "场景：用户注册-用户登录-修改用户"}, {"name": "story", "value": "用例--注册/登录/修改--预期失败"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_02_register_login_update"}, {"name": "subSuite", "value": "TestRegLogUpdate"}, {"name": "host", "value": "192.168.10.5"}, {"name": "thread", "value": "23381-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_02_register_login_update"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}