{"uuid": "a0f497d7-9c5b-4d51-8729-2c3f31a991c3", "children": ["76bf7c07-a289-45f9-9ede-344f1a707158", "8361a341-8678-4c87-9e28-b2bec7311579", "9b164bd3-22f1-44c5-a9fb-69b987987414", "13eb1f31-7108-4c10-b29b-30b2301f6379", "80d59f91-66ea-4807-a5ee-63983fcbd319"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/testcases/conftest.py\", line 57, in login_fixture\n    yield loginInfo.response.json()\n"}, "steps": [{"name": "前置步骤 ==>> 管理员用户登录", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}], "start": 1744991016938, "stop": 1744991016938}], "start": 1744991016864, "stop": 1744991016939}], "start": 1744991016864, "stop": 1744991019198}